import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header.jsx";
import { ConvexClientProvider } from "@/components/convex-client-provider.jsx";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/logos/logo-s.png" sizes="any"/>
      </head>
      <body
        className={`${inter.className}`}>
        <ClerkProvider>
          <ConvexClientProvider>
            <Header />

            <main className="min-h-screen">
              {children}
              <Toaster richColors/>
            </main>
            
          </ConvexClientProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
